"""new revision

Revision ID: 5f620c6e6d53
Revises: 476c2091116f
Create Date: 2023-06-25 19:52:20.082255

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '5f620c6e6d53'
down_revision = '476c2091116f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
                    sa.Column('event_type', sa.String(), nullable=False),
                    sa.Column('message', sa.Text(), nullable=False),
                    sa.Column('kpd_diff', sa.Integer(), nullable=False),
                    sa.Column('event_target_id', sa.Integer(), nullable=True),
                    sa.Column('event_initiator_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['event_initiator_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('events')
    # ### end Alembic commands ###
